spring:
  cloud:
    gateway:
      routes:
      - id: college-service
        uri: http://localhost:1111/
        predicates:
        - Path=/college/**
        
      - id: student-service
        uri: http://localhost:2222/
        predicates:
        - Path=/student/**
        
      
        